# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'gradle'
    directory: '/' # Location of package manifests
    schedule:
      interval: 'daily'
    target-branch: 'develop'
  - package-ecosystem: 'gradle'
    directory: '/basebibliotek-generated' # Location of package manifests
    schedule:
      interval: 'daily'
    target-branch: 'develop'
  - package-ecosystem: 'gradle'
    directory: '/alma-generated' # Location of package manifests
    schedule:
      interval: 'daily'
    target-branch: 'develop'
  - package-ecosystem: 'gradle'
    directory: '/alma-integrations' # Location of package manifests
    schedule:
      interval: 'daily'
    target-branch: 'develop'
  - package-ecosystem: 'gradle'
    directory: '/basebibliotek-fetch-cronjob'
    schedule:
      interval: 'daily'
    target-branch: 'develop'
