plugins {
    id 'java'
    id 'nebula.lint'
    id 'jacoco-report-aggregation'
}

repositories {
    mavenCentral()
    maven { url 'https://jitpack.io' }
}

subprojects {
    subproject ->
        if (!subproject.name.endsWith("generated")) {
            subproject.pluginManager.apply('pmd')
            subproject.pluginManager.apply('checkstyle')
            subproject.pluginManager.apply('jacoco')


            pmd {
                toolVersion = '7.25.0'
                ruleSetConfig = rootProject.resources.text.fromFile('config/pmd/ruleset.xml')
                ruleSets = []
                ignoreFailures = false
            }

            checkstyle {
                toolVersion = '13.6.0'
                configFile = rootProject.resources.text.fromFile('config/checkstyle/checkstyle.xml').asFile()
                configProperties.checkstyleSuppressionsPath =
                        rootProject.resources.text
                                .fromFile('config/checkstyle/checkstyle-suppressions.xml').asFile()
                showViolations = true
            }

            jacoco {
                toolVersion = '0.8.15'
            }

            jacocoTestReport {
                reports {
                    html.outputLocation.set(layout.buildDirectory.dir("reports/jacoco"))
                }
            }

            // SAM handles packaging, disable default jar task for function modules
            jar.enabled = false
        }
}

// Running tests using gradle
tasks.named('test', Test) {
    useJUnitPlatform()
    failFast = true
    finalizedBy jacocoTestReport
    testLogging {
       events 'skipped', 'failed' //, 'passed'
    }
}

tasks.named('jacocoTestReport', JacocoReport) {

    reports {
        html.required.set(true)
        xml.required.set(false)
        csv.required.set(false)
    }
}

tasks.named('jacocoTestCoverageVerification', JacocoCoverageVerification) {
    violationRules {
        rule {
            limit {
                counter = 'METHOD'
                value = 'COVEREDRATIO'
                minimum = 1.0
            }
        }

        rule {
            limit {
                counter = 'CLASS'
                value = 'COVEREDRATIO'
                minimum = 1.0
            }
        }
    }
    dependsOn jacocoTestReport
}

tasks.withType(Checkstyle).configureEach{
    reports {
        html.required
        html.stylesheet rootProject.resources.text.fromFile('config/checkstyle/checkstyle-simple.xsl')
    }
}

// Lint dependencies on gradle build using nebula lint
gradleLint {
    rules = ['all-dependency']
    reportFormat = 'html'
    reportOnlyFixableViolations = true
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'utf-8'
}

// Verify test coverage is over minimum required values
tasks.named('check').configure {
    dependsOn tasks.named('jacocoTestCoverageVerification')
}
