version: 0.2

env:
  shell: bash

phases:

  install:
    runtime-versions:
      java: corretto11
      ruby: 2.6
    commands:
      - pip3 install --upgrade cfn-lint
      # Upgrade AWS CLI to the latest version
      # Install aws-sam-cli
      - pip3 install aws-sam-cli
      # Install cfn_nag
      - gem install cfn-nag

  pre_build:
    commands:
      - echo "pre_build steps for revision ${CODEBUILD_RESOLVED_SOURCE_VERSION}..."
      - env
      - aws --version


  build:
    commands:
      - echo Build started on `date`
      # Use AWS SAM to build and package the application by using AWS CloudFormation
      - sam build
      - sam package --s3-bucket $S3_BUCKET --output-template-file packaged.yml

    post_build:
      commands:
        - echo Build completed on `date`
        - echo Files
        - ls -l

artifacts:
  files:
    - '**/*'
