AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS
  Sample SAM Template for AWS
Parameters:
  BasebibliotekXmlBucketName:
    Type: String
    Default: "basebibliotek-txt-files"
    Description: Name of bucket for basebibliotek txt file
  SharedConfigBucketName:
    Type: AWS::SSM::Parameter::Value<String>
    Default: "shared-config-bucket-name"
    Description: Parameter should be set manually in systems-manager
  LibCodeToAlmaCodeFilePath:
    Type: String
    Default: 'fullLibCodeToAlmaCodeMapping.json'
    Description: 'Path to the libCode to almaCode mapping file'
  ReportBucketName:
    Type: String
    Default: 'basebibliotek-report'
  BasebibliotekUsername:
    Type: String
    Default: "{{resolve:secretsmanager:basebibliotek-login:SecretString:USERNAME}}"
  BasebibliotekPassword:
    Type: String
    Default: "{{resolve:secretsmanager:basebibliotek-login:SecretString:PASSWORD}}"
  BasebibliotekExportUrl:
    Type: String
    Default: 'https://www.nb.no/baser/bibliotek/eksport/biblev/'
  BasebibliotekRestUrl:
    Type: String
    Default: 'https://www.nb.no/basebibliotek/rest/bibnr/'
  IllServerUri:
    Type: String
    Default: 'eu01.alma.exlibrisgroup.com'
  AlmaApiHost:
    Type: String
    Default: 'https://api-eu.hosted.exlibrisgroup.com/almaws/v1/'

Globals:
  Function:
    Timeout: 900
    MemorySize: 1798
    Runtime: java21
  Api:
    Cors:
      AllowMethods: "'POST,OPTIONS'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"
Resources:
  ApiAccessLogGroup:
    Type: AWS::Logs::LogGroup

  ResourceSharingPartnerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: alma-integrations
      Handler: no.sikt.rsp.ResourceSharingPartnerHandler::handleRequest
      Role: !GetAtt ResourceSharingPartnerHandlerRole.Arn
      ReservedConcurrentExecutions: 1
      Environment:
        Variables:
          REPORT_BUCKET: !Sub '${ReportBucketName}-${AWS::AccountId}'
          BASEBIBLIOTEK_REST_URL: !Ref BasebibliotekRestUrl
          SHARED_CONFIG_BUCKET: !Ref SharedConfigBucketName
          LIB_CODE_TO_ALMA_CODE_MAPPING_FILE_PATH: !Ref LibCodeToAlmaCodeFilePath
          ILL_SERVER: !Ref IllServerUri
          ALMA_API_HOST: !Ref AlmaApiHost
          ALMA_APIKEY: '{{resolve:secretsmanager:ALMA_APIKEY:SecretString:ALMA_APIKEY}}'
      Events:
        BasebibliotekFileUploadForRsp:
          Type: S3
          Properties:
            Bucket: !Ref BasebibliotekXmlBucket
            Events: 's3:ObjectCreated:*'
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: 'rsp/'
                  - Name: suffix
                    Value: '.txt'

  BasebibliotekFetchCronjob:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: basebibliotek-fetch-cronjob
      Handler: no.sikt.BasebibliotekFetchHandler::handleRequest
      Role: !GetAtt BasebibliotekFetchCronjobRole.Arn
      Environment:
        Variables:
          BASEBIBLIOTEK_USERNAME: !Ref BasebibliotekUsername
          BASEBIBLIOTEK_PASSWORD: !Ref BasebibliotekPassword
          BASEBIBLIOTEK_EXPORT_URL: !Ref BasebibliotekExportUrl
          BASEBIBLIOTEK_XML_BUCKET:  !Ref BasebibliotekXmlBucket
      Events:
        ScheduledUpdate:
          Type: Schedule
          Properties:
            Schedule: cron(0 20 * * ? *)

  LibraryUserManagementFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: alma-integrations
      Handler: no.sikt.lum.LibraryUserManagementHandler::handleRequest
      Role: !GetAtt LibraryUserManagementHandlerRole.Arn
      ReservedConcurrentExecutions: 10
      Environment:
        Variables:
          REPORT_BUCKET: !Sub '${ReportBucketName}-${AWS::AccountId}'
          BASEBIBLIOTEK_REST_URL: !Ref BasebibliotekRestUrl
          SHARED_CONFIG_BUCKET: !Ref SharedConfigBucketName
          ALMA_API_HOST: !Ref AlmaApiHost
      Events:
        BasebibliotekFileUploadForLum:
          Type: S3
          Properties:
            Bucket: !Ref BasebibliotekXmlBucket
            Events: 's3:ObjectCreated:*'
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: 'lum/'
                  - Name: suffix
                    Value: '.txt'

  ResourceSharingPartnerHandlerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole

  BasebibliotekFetchCronjobRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole

  LibraryUserManagementHandlerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole

  DefaultLambdaPermissions:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub DefaultLambdaPermissions-${AWS::StackName}
      Roles:
        - !Ref ResourceSharingPartnerHandlerRole
        - !Ref BasebibliotekFetchCronjobRole
        - !Ref LibraryUserManagementHandlerRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              - lambda:InvokeFunction
            Resource: "*"

  BasebibliotekXmlBucketAccessPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub BasebibliotekXmlBucketAccessPolicy-${AWS::StackName}
      Roles:
        - !Ref ResourceSharingPartnerHandlerRole
        - !Ref BasebibliotekFetchCronjobRole
        - !Ref LibraryUserManagementHandlerRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 's3:*'
            Resource:
              - !Sub 'arn:aws:s3:::${BasebibliotekXmlBucketName}-${AWS::AccountId}*'

  SharedConfigBucketAccessPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub SharedConfigBucketAccessPolicy-${AWS::StackName}
      Roles:
        - !Ref ResourceSharingPartnerHandlerRole
        - !Ref LibraryUserManagementHandlerRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 's3:*'
            Resource:
              -  !Sub "arn:aws:s3:::${SharedConfigBucketName}*"

  ReportBucketAccessPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub ReportBucketAccessPolicy-${AWS::StackName}
      Roles:
        - !Ref ResourceSharingPartnerHandlerRole
        - !Ref LibraryUserManagementHandlerRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 's3:*'
            Resource:
              - !Sub 'arn:aws:s3:::${ReportBucketName}-${AWS::AccountId}*'

  AlmaKeysAccessPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub AlmaKeysAccessPolicy-${AWS::StackName}
      Roles:
        - !Ref LibraryUserManagementHandlerRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource:
              - !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:alma_api_keys_full*'

  BasebibliotekXmlBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: !Sub "${BasebibliotekXmlBucketName}-${AWS::AccountId}"
      LifecycleConfiguration:
        Rules:
          - Id: DeleteContentAfter3Days
            Status: Enabled
            ExpirationInDays: 3

  ReportBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: !Sub "${ReportBucketName}-${AWS::AccountId}"
