[versions]
junit-jupiter = '6.1.0'
nva-commons = '2.8.2'
jackson-annotations = '2.22'
jackson = '2.22.0'
mockito = '5.23.0'
hamcrest = '3.0'
aws-lambda-java-core = '1.4.0'
aws-lambda-java-events = '3.16.1'
aws-lambda-java-log4j2 = '1.6.4'
log4j = '2.26.0'
log4jApi = '2.26.0'
slf4j-api = '2.0.18'
slf4j-impl = '2.26.0'
nva-language = '1.2.2'
wiremock = '3.13.2'
jaxb = '4.0.9'
gson = '2.14.0'
apache-commons = '3.20.0'
xml-bind = '4.0.5'
aws-sdk = '2.46.20'

# Jaxb group
jaxb-xjc = '4.0.9'
jaxb-impl = '4.0.9'
jakarata-xml-api = '4.0.5'
activation-api = '2.1.4'

[libraries]

#Test

junit-jupiter-api = { group = 'org.junit.jupiter', name = 'junit-jupiter-api', version.ref = 'junit-jupiter' }
junit-jupiter-engine = { group = 'org.junit.jupiter', name = 'junit-jupiter-engine', version.ref = 'junit-jupiter' }
junit-jupiter-params = { group = 'org.junit.jupiter', name = 'junit-jupiter-params', version.ref = 'junit-jupiter' }


mockito-core = { group = 'org.mockito', name = 'mockito-core', version.ref = 'mockito' }
hamcrest = { group = 'org.hamcrest', name = 'hamcrest', version.ref = 'hamcrest' }
hamcrest-core = { group = 'org.hamcrest', name = 'hamcrest-core', version.ref = 'hamcrest' }

nva-testutils = { group = 'com.github.bibsysdev', name = 'nvatestutils', version.ref = 'nva-commons' }
nva-logutils = { group = 'com.github.bibsysdev', name = 'logutils', version.ref = 'nva-commons' }

wiremock-standalone = { group = 'org.wiremock', name = 'wiremock-standalone', version.ref = 'wiremock' }

#Regular

nva-commons-core = { group = 'com.github.bibsysdev', name = 'core', version.ref = 'nva-commons' }
nva-s3 = { group = 'com.github.bibsysdev', name = 's3', version.ref = 'nva-commons' }
nva-language = { group = 'com.github.bibsysdev', name = 'nva-language', version.ref = 'nva-language' }
nva-secrets = { group = 'com.github.bibsysdev', name = 'secrets', version.ref = 'nva-commons' }

jackson-databind = { group = 'com.fasterxml.jackson.core', name = 'jackson-databind', version.ref = 'jackson' }
jackson-annotations = { group = 'com.fasterxml.jackson.core', name = 'jackson-annotations', version.ref = 'jackson-annotations' }
jackson-core = { group = 'com.fasterxml.jackson.core', name = 'jackson-core', version.ref = 'jackson' }

aws-lambda-java-core = { group = 'com.amazonaws', name = 'aws-lambda-java-core', version.ref = 'aws-lambda-java-core' }
aws-lambda-java-events = { group = 'com.amazonaws', name = 'aws-lambda-java-events', version.ref = 'aws-lambda-java-events' }
aws-lambda-java-log4j2 = { group = 'com.amazonaws', name = 'aws-lambda-java-log4j2', version.ref = 'aws-lambda-java-log4j2' }
aws-sdk2-secrets = { group = 'software.amazon.awssdk', name = 'secretsmanager', version.ref = 'aws-sdk' }
aws-sdk2-s3 = { group = 'software.amazon.awssdk', name = 's3', version.ref = 'aws-sdk' }
aws-sdk-core = { group = 'software.amazon.awssdk', name = 'sdk-core', version.ref = 'aws-sdk' }
aws-core = { group = 'software.amazon.awssdk', name = 'aws-core', version.ref = 'aws-sdk' }
aws-regions = { group = 'software.amazon.awssdk', name = 'regions', version.ref = 'aws-sdk' }
aws-utils = { group = 'software.amazon.awssdk', name = 'utils', version.ref = 'aws-sdk' }
aws-http-client-spi = { group = 'software.amazon.awssdk', name = 'http-client-spi', version.ref = 'aws-sdk' }

log4j-api = { group = 'org.apache.logging.log4j', name = 'log4j-api', version.ref = 'log4jApi' }
log4j-core = { group = 'org.apache.logging.log4j', name = 'log4j-core', version.ref = 'log4j' }
log4j-slf4j-impl = { group = 'org.apache.logging.log4j', name = 'log4j-slf4j2-impl', version.ref = 'slf4j-impl' }
slf4j-api = { group = 'org.slf4j', name = 'slf4j-api', version.ref = 'slf4j-api' }

jaxb-runtime = { group = 'org.glassfish.jaxb', name = 'jaxb-runtime', version.ref = 'jaxb' }

google-gson = { group = 'com.google.code.gson', name = 'gson', version.ref = 'gson' }

apache-commons-lang3 = { group = 'org.apache.commons', name = 'commons-lang3', version.ref = 'apache-commons' }

jakarta-xml-bind = { group = 'jakarta.xml.bind', name = 'jakarta.xml.bind-api', version.ref = 'xml-bind' }

# Jaxb group
jaxb-xjc = { group = 'com.sun.xml.bind', name = 'jaxb-xjc', version.ref = 'jaxb-xjc' }
jaxb-impl = { group = 'com.sun.xml.bind', name = 'jaxb-impl', version.ref = 'jaxb-impl' }
jakarata-xml-api = { group = 'jakarta.xml.bind', name = 'jakarta.xml.bind-api', version.ref = 'jakarata-xml-api' }
activation-api = { group = 'jakarta.activation', name = 'jakarta.activation-api', version.ref = 'activation-api' }

[bundles]

jaxb-group = [ 'jaxb-xjc', 'jaxb-impl', 'jakarata-xml-api', 'activation-api' ]
logging = [ 'log4j-api', 'log4j-core', 'slf4j-api', 'log4j-slf4j-impl' ]
aws-lambda = [ 'aws-lambda-java-core', 'aws-lambda-java-events', 'aws-lambda-java-log4j2' ]
testing = [ 'junit-jupiter-api', 'junit-jupiter-params', 'junit-jupiter-engine', 'mockito-core', 'hamcrest', 'hamcrest-core', 'nva-testutils', 'nva-logutils' ]
